#!/bin/zsh

# file: tcp_read_tool.sh
#

# This script reads a binary TCP capture file generated by the tcpdump command.
# The output is displayed in hexadecimal format.
#

# run the tcpdump command (sudo privilege not required)
#
tcpdump -qns 0 -X -r $1

#
# end of file
